spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: shanuka
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    #    Flyway is an open-source database migration tool.
    #    It helps you manage and version your database schema changes in an automated and reliable way.
    #    Think of it as version control (like Git) for your database.
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 9040
