services:
  postgres:
    image: postgres:14
    container_name: micro_app
    environment:
      POSTGRES_USER: shanuka
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - micro-network
    restart: unless-stopped

networks:
  micro-network:
    driver: bridge

volumes:
  postgres_data: